const { withAndroidManifest } = require("expo/config-plugins");

/**
 * Strips the Google code-scanner activity from PRODUCTION builds.
 *
 * Why this exists
 * ---------------
 * Play flagged this against 2.4.1 (versionCode 8) under "Remove resizability and
 * orientation restrictions ... to support large screen devices":
 *
 *   <activity android:name="com.google.mlkit.vision.codescanner.internal
 *     .GmsBarcodeScanningDelegateActivity" android:screenOrientation="PORTRAIT" />
 *
 * RanDOM WisDOM never scans barcodes. The activity comes from expo-dev-client:
 * node_modules/expo-dev-launcher/android/build.gradle declares
 *
 *   implementation "com.google.android.gms:play-services-code-scanner:16.1.0"
 *
 * as a plain `implementation` (not debugImplementation), so the library manifest, and
 * its portrait-locked activity, is merged into release builds too, even though
 * dev-launcher's release source set is only a stub. From Android 16 the OS ignores
 * the orientation lock on large screens, and Play warns about it.
 *
 * Development builds (APP_VARIANT=development, which covers both the `development`
 * and `preview` EAS profiles) are left alone, because there the dev launcher's
 * "Scan QR code" button really uses this activity.
 *
 * Same mechanism as withoutAudioRecordingService: `tools:node="remove"` tells the
 * manifest merger to drop the element contributed by the library. android/ is
 * gitignored and regenerated by prebuild, so this must be a config plugin.
 *
 * Verify in the built AAB's merged manifest, not the prebuild output: prebuild only
 * emits the pre-merge app manifest, so the proof there is the remove directive.
 *
 * Delete this plugin if expo-dev-launcher ever moves the dependency to
 * debugImplementation, or if expo-dev-client is removed from the app.
 */

const TOOLS_NAMESPACE = "http://schemas.android.com/tools";
const ACTIVITY =
  "com.google.mlkit.vision.codescanner.internal.GmsBarcodeScanningDelegateActivity";

const withoutDevLauncherBarcodeScanner = (config) =>
  withAndroidManifest(config, (config) => {
    if (process.env.APP_VARIANT === "development") return config;

    const manifest = config.modResults;
    manifest.manifest.$ = manifest.manifest.$ || {};
    manifest.manifest.$["xmlns:tools"] = TOOLS_NAMESPACE;

    const application = manifest.manifest.application?.[0];
    if (!application) {
      throw new Error(
        "[withoutDevLauncherBarcodeScanner] No <application> node in AndroidManifest.xml — " +
          "the manifest shape changed and this plugin needs revisiting."
      );
    }

    application.activity = application.activity || [];

    // Idempotent: prebuild can run this against an already-modified manifest.
    const alreadyPresent = application.activity.some(
      (activity) => activity.$?.["android:name"] === ACTIVITY
    );

    if (!alreadyPresent) {
      application.activity.push({
        $: { "android:name": ACTIVITY, "tools:node": "remove" },
      });
    }

    return config;
  });

module.exports = withoutDevLauncherBarcodeScanner;
