const { withAndroidManifest } = require("expo/config-plugins");

/**
 * Strips expo-audio's microphone foreground service from the merged manifest.
 *
 * Why this exists
 * ---------------
 * expo-audio declares two foreground services in its own library manifest:
 *
 *   AudioControlsService   foregroundServiceType="mediaPlayback"
 *   AudioRecordingService  foregroundServiceType="microphone"
 *
 * RanDOM WisDOM only ever plays audio — nothing under src/ imports useAudioRecorder,
 * prepareToRecordAsync or RecordingPresets. The recording service is dead weight, and
 * because "microphone" is a restricted foreground service type it is half of the
 * "Restricted foreground service types" issue Play raised against the 2.3.0 release
 * (the other half being expo-notifications' BOOT_COMPLETED receiver).
 *
 * The expo-audio config plugin exposes `recordAudioAndroid: false`, but that only omits
 * RECORD_AUDIO from the list the plugin adds to OUR manifest — it removes nothing. Both
 * the permission and the <service> element live in expo-audio's own library manifest and
 * are introduced by the manifest merger, which cannot be edited from a config plugin
 * option. The merger's `tools:node="remove"` directive is the supported way to delete
 * them.
 *
 * Split across two places, deliberately:
 *   - the <service> here, because there is no first-party config field for it;
 *   - the RECORD_AUDIO permission via `android.blockedPermissions` in app.config.js,
 *     which is the supported field and emits the identical directive. See the comment
 *     there — it is the other half of this fix and the two should move together.
 *
 * android/ is gitignored and regenerated by prebuild, so this has to be a config plugin
 * rather than a hand edit — a hand edit would vanish on the next `expo prebuild --clean`.
 *
 * If audio recording is ever added to the app, delete this plugin and drop BOTH the
 * `recordAudioAndroid: false` option and the `blockedPermissions` entry in app.config.js.
 */

const TOOLS_NAMESPACE = "http://schemas.android.com/tools";
const SERVICE = "expo.modules.audio.service.AudioRecordingService";

const withoutAudioRecordingService = (config) =>
  withAndroidManifest(config, (config) => {
    const manifest = config.modResults;

    // The `tools:` prefix has to be declared on <manifest> or the merger errors out.
    manifest.manifest.$ = manifest.manifest.$ || {};
    manifest.manifest.$["xmlns:tools"] = TOOLS_NAMESPACE;

    const application = manifest.manifest.application?.[0];
    if (!application) {
      throw new Error(
        "[withoutAudioRecordingService] No <application> node in AndroidManifest.xml — " +
          "the manifest shape changed and this plugin needs revisiting."
      );
    }

    application.service = application.service || [];

    // Idempotent: prebuild can run this against an already-modified manifest.
    const alreadyPresent = application.service.some(
      (service) => service.$?.["android:name"] === SERVICE
    );

    if (!alreadyPresent) {
      application.service.push({
        $: { "android:name": SERVICE, "tools:node": "remove" },
      });
    }

    return config;
  });

module.exports = withoutAudioRecordingService;
